import { LoaderCircle, Inbox, X, UploadCloud } from 'lucide-react'; import { useEffect } from 'react'; import type { HTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes } from 'react'; import { initials } from '../../utils/formatters';
export function GlassCard({children,className='',interactive=false,...props}:{children:ReactNode;className?:string;interactive?:boolean}&HTMLAttributes<HTMLElement>){return <section className={`glass-panel ${interactive?'hoverable':''} ${className}`} {...props}>{children}</section>;}
export function GlassButton({children,onClick,variant='primary',size='md',disabled=false,type='button',loading=false,className='' }:{children:ReactNode;onClick?:()=>void;variant?:'primary'|'secondary'|'ghost'|'danger';size?:'sm'|'md';disabled?:boolean;type?:'button'|'submit';loading?:boolean;className?:string}){return <button type={type} onClick={onClick} disabled={disabled||loading} className={`btn btn-${variant} ${size==='sm'?'btn-sm':''} ${className}`}>{loading&&<LoaderCircle size={15} className="spin"/>}{children}</button>;}
export function GlassInput({label,error,...props}:{label:string;error?:string}&InputHTMLAttributes<HTMLInputElement>){const id=props.id??`field-${label.replaceAll(' ','-')}`;return <div className="field"><label htmlFor={id}>{label}</label><input id={id} className="input" aria-describedby={error?`${id}-error`:undefined} {...props}/>{error&&<small id={`${id}-error`} className="error">{error}</small>}</div>;}
export function GlassSelect({label,children,...props}:{label:string;children:ReactNode}&SelectHTMLAttributes<HTMLSelectElement>){const id=props.id??`field-${label.replaceAll(' ','-')}`;return <div className="field"><label htmlFor={id}>{label}</label><select id={id} className="select" {...props}>{children}</select></div>;}
export function Avatar({name,small=false}:{name:string;small?:boolean}){return <span className={`avatar ${small?'sm':''}`} aria-label={name}>{initials(name)}</span>;}
export function StatusBadge({status}:{status:string}){return <span className={`status ${status.toLowerCase().replaceAll(' ','_')}`}>{status.replaceAll('_',' ')}</span>;}
export function StatCard({label,value,icon,trend}:{label:string;value:string;icon:ReactNode;trend?:string}){return <GlassCard className="stat" interactive><div className="stat-top"><span>{label}</span><span className="stat-icon">{icon}</span></div><strong className="stat-value">{value}</strong>{trend&&<span className="trend">↗ {trend}</span>}</GlassCard>;}
export function EmptyState({icon,title,body,action}:{icon?:ReactNode;title:string;body:string;action?:ReactNode}){return <div className="empty">{icon??<Inbox size={36}/>}<h3>{title}</h3><p>{body}</p>{action}</div>;}
export function LoadingSkeleton({lines=3}:{lines?:number}){return <div className="stack">{Array.from({length:lines},(_,i)=><div key={i} className="glass-inset" style={{height:42,opacity:.62}}/>)}</div>;}
export function Stepper({steps,current}:{steps:string[];current:number}){return <div className="steps">{steps.map((step,index)=><div key={step} className={`step ${index<current?'done':''} ${index===current?'active':''}`}>{step}</div>)}</div>;}
export function Tabs({tabs,active,onChange}:{tabs:string[];active:string;onChange:(tab:string)=>void}){return <div className="tab-row" role="tablist">{tabs.map((tab)=><button key={tab} role="tab" aria-selected={active===tab} className={`tab ${active===tab?'active':''}`} onClick={()=>onChange(tab)}>{tab}</button>)}</div>;}
export function GlassModal({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};if(open)window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[open,onClose]);if(!open)return null;return <div className="modal-scrim" role="presentation" onMouseDown={onClose}><div className="glass-panel modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={(e)=>e.stopPropagation()}><div className="section-title"><h2>{title}</h2><button className="icon-btn" onClick={onClose} aria-label="Close dialog"><X size={19}/></button></div>{children}</div></div>;}
export function GlassDrawer({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){if(!open)return null;return <><button className="drawer-scrim" aria-label="Close panel" onClick={onClose}/><aside className="glass-panel drawer"><div className="section-title"><h2>{title}</h2><button className="icon-btn" onClick={onClose} aria-label="Close panel"><X size={19}/></button></div>{children}</aside></>;}
export function FileUpload({onFiles}:{onFiles:(files:File[])=>void}){return <label className="glass-inset upload-zone"><UploadCloud size={28}/><h3>Drop evidence here</h3><p className="muted tiny">Photos, soil tests, satellite images, or land-title documents</p><input hidden type="file" multiple onChange={(e)=>onFiles(Array.from(e.target.files??[]))}/><span className="btn btn-secondary btn-sm">Choose files</span></label>;}
export function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:ReactNode}){return <div className="page-head"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1 className="display">{title}</h1><p>{description}</p></div>{action}</div>;}
export function ProgressRing({value,label}:{value:number;label:string}){return <div style={{display:'grid',placeItems:'center',width:112,height:112,borderRadius:'50%',background:`conic-gradient(var(--accent) ${value*3.6}deg, rgba(255,255,255,.08) 0)`}}><div style={{display:'grid',placeItems:'center',width:88,height:88,borderRadius:'50%',background:'#091c14'}}><b>{value}</b><small className="muted">{label}</small></div></div>;}
export function DataTable({headers,children}:{headers:string[];children:ReactNode}){return <div className="data-table-wrap"><table className="data-table"><thead><tr>{headers.map((h)=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
export function Toast({message}:{message:string}){return <div className="glass-panel toast" role="status">{message}</div>;}
